import Wrapper from '../components/Wrapper'
import Head from 'next/head'

import '../styles/globals.css'
import Private from '../components/Private'
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Overpay App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/appIcon.svg" />
      </Head>
      <Private>
        <Wrapper>
          <Component {...pageProps} />
        </Wrapper>
      </Private>
    </>
    
    
  )
}

export default MyApp
